--  Generated by scripts/generate-constants.sh. Do not edit.
--
--  Regenerate on a Linux host, or through the repository's Linux
--  container, whenever the target kernel headers change. The
--  companion verify-constants.sh regenerates into a temporary file
--  and diffs, so drift between this file and the kernel is a test
--  failure rather than a surprise at run time.
package Flyology_VFIO.Thin.Constants
  with Preelaborate
is

   ------------------------------------------------------------------
   --  Request numbers taken on a container file descriptor
   ------------------------------------------------------------------

   --  VFIO_GET_API_VERSION: no argument; the version is the result.
   Container_Get_API_Version          : constant := 15204;

   --  VFIO_CHECK_EXTENSION: argument is an extension number, not a struct.
   Container_Check_Extension          : constant := 15205;

   --  VFIO_SET_IOMMU: argument is an IOMMU type. Requires a group already
   --  attached.
   Container_Set_IOMMU                : constant := 15206;

   --  VFIO_IOMMU_GET_INFO: shares its number with
   --  VFIO_DEVICE_GET_PCI_HOT_RESET_INFO on a device fd.
   Container_Get_IOMMU_Info           : constant := 15216;

   --  VFIO_IOMMU_MAP_DMA: shares its number with
   --  VFIO_DEVICE_PCI_HOT_RESET on a device fd.
   Container_Map_DMA                  : constant := 15217;

   --  VFIO_IOMMU_UNMAP_DMA: shares its number with
   --  VFIO_DEVICE_QUERY_GFX_PLANE on a device fd.
   Container_Unmap_DMA                : constant := 15218;

   ------------------------------------------------------------------
   --  Request numbers taken on a group file descriptor
   ------------------------------------------------------------------

   --  VFIO_GROUP_GET_STATUS: fills a struct carrying the viability flag.
   Group_Get_Status                   : constant := 15207;

   --  VFIO_GROUP_SET_CONTAINER: argument is a container fd, not a struct.
   Group_Set_Container                : constant := 15208;

   --  VFIO_GROUP_UNSET_CONTAINER: no argument.
   Group_Unset_Container              : constant := 15209;

   --  VFIO_GROUP_GET_DEVICE_FD: argument is a NUL-terminated name; the
   --  new fd is the result.
   Group_Get_Device_FD                : constant := 15210;

   ------------------------------------------------------------------
   --  Request numbers taken on a device file descriptor
   ------------------------------------------------------------------

   --  VFIO_DEVICE_GET_INFO: region and interrupt counts.
   Device_Get_Info                    : constant := 15211;

   --  VFIO_DEVICE_GET_REGION_INFO: size, offset and flags of one region.
   Device_Get_Region_Info             : constant := 15212;

   --  VFIO_DEVICE_GET_IRQ_INFO: vector count and capabilities of one
   --  index.
   Device_Get_IRQ_Info                : constant := 15213;

   --  VFIO_DEVICE_SET_IRQS: struct with a variable-length tail of
   --  eventfds.
   Device_Set_IRQs                    : constant := 15214;

   --  VFIO_DEVICE_RESET: no argument. Bus mastering must be re-enabled
   --  afterwards.
   Device_Reset                       : constant := 15215;

   ------------------------------------------------------------------
   --  IOMMU types and extensions
   ------------------------------------------------------------------

   --  The only API version this interface has ever had.
   API_Version                        : constant := 0;

   --  The original type1 IOMMU.
   Type1_IOMMU                        : constant := 1;

   --  Type1 version 2, which this crate requires.
   Type1_V2_IOMMU                     : constant := 3;

   --  No-IOMMU mode, which supports no ioctl beyond CHECK_EXTENSION and
   --  in which a device consumes physical addresses. Not usable here.
   No_IOMMU                           : constant := 8;

   ------------------------------------------------------------------
   --  Flags
   ------------------------------------------------------------------

   --  Every device in the IOMMU group is bound to vfio-pci or unbound.
   Group_Flag_Viable                  : constant := 16#1#;

   --  The group is already attached to a container.
   Group_Flag_Container_Set           : constant := 16#2#;

   --  The device can reset.
   Device_Flag_Reset                  : constant := 16#1#;

   --  The device is vfio-pci.
   Device_Flag_PCI                    : constant := 16#2#;

   --  Readable with pread.
   Region_Flag_Read                   : constant := 16#1#;

   --  Writable with pwrite.
   Region_Flag_Write                  : constant := 16#2#;

   --  Mappable. Absent for config space and for I/O port BARs.
   Region_Flag_Mmap                   : constant := 16#4#;

   --  The reply carries a capability chain, which needs a second call.
   Region_Flag_Caps                   : constant := 16#8#;

   --  The device may read.
   DMA_Flag_Read                      : constant := 16#1#;

   --  The device may write.
   DMA_Flag_Write                     : constant := 16#2#;

   --  No data tail.
   IRQ_Set_Data_None                  : constant := 16#1#;

   --  The tail is an array of eventfd descriptors.
   IRQ_Set_Data_Eventfd               : constant := 16#4#;

   --  Set what the interrupt triggers.
   IRQ_Set_Action_Trigger             : constant := 16#20#;

   --  This interrupt index can signal an eventfd.
   IRQ_Info_Eventfd                   : constant := 16#1#;

   --  The iova_pgsizes field is valid.
   IOMMU_Info_Page_Sizes              : constant := 16#1#;

   ------------------------------------------------------------------
   --  PCI region and interrupt indices
   ------------------------------------------------------------------

   --  First base address register.
   PCI_BAR0_Region                    : constant := 0;

   --  Expansion ROM.
   PCI_ROM_Region                     : constant := 6;

   --  Configuration space. Never mappable: read and written with pread
   --  and pwrite at this region's offset.
   PCI_Config_Region                  : constant := 7;

   --  Regions a PCI device has.
   PCI_Region_Count                   : constant := 9;

   --  Legacy pin interrupt.
   PCI_INTX_IRQ                       : constant := 0;

   --  MSI.
   PCI_MSI_IRQ                        : constant := 1;

   --  MSI-X.
   PCI_MSIX_IRQ                       : constant := 2;

   --  Interrupt indices a PCI device has.
   PCI_IRQ_Count                      : constant := 5;

   ------------------------------------------------------------------
   --  Struct sizes and field offsets, for the layout assertions
   --
   --  The Ada records in the parent package pin their layout with
   --  representation clauses and check it against these with
   --  pragma Compile_Time_Error, so a kernel that moves a field
   --  breaks the build rather than the device.
   ------------------------------------------------------------------

   Group_Status_Size                  : constant := 8;
   Group_Status_Argsz_Offset          : constant := 0;
   Group_Status_Flags_Offset          : constant := 4;

   Device_Info_Size                   : constant := 20;
   Device_Info_Argsz_Offset           : constant := 0;
   Device_Info_Flags_Offset           : constant := 4;
   Device_Info_Num_Regions_Offset     : constant := 8;
   Device_Info_Num_IRQs_Offset        : constant := 12;

   Region_Info_Size                   : constant := 32;
   Region_Info_Argsz_Offset           : constant := 0;
   Region_Info_Flags_Offset           : constant := 4;
   Region_Info_Index_Offset           : constant := 8;
   Region_Info_Cap_Offset_Offset      : constant := 12;
   Region_Info_Size_Offset            : constant := 16;
   Region_Info_Offset_Offset          : constant := 24;

   IRQ_Info_Size                      : constant := 16;
   IRQ_Info_Argsz_Offset              : constant := 0;
   IRQ_Info_Flags_Offset              : constant := 4;
   IRQ_Info_Index_Offset              : constant := 8;
   IRQ_Info_Count_Offset              : constant := 12;

   IRQ_Set_Header_Size                : constant := 20;
   IRQ_Set_Argsz_Offset               : constant := 0;
   IRQ_Set_Flags_Offset               : constant := 4;
   IRQ_Set_Index_Offset               : constant := 8;
   IRQ_Set_Start_Offset               : constant := 12;
   IRQ_Set_Count_Offset               : constant := 16;
   IRQ_Set_Data_Offset                : constant := 20;

   IOMMU_Info_Size                    : constant := 24;
   IOMMU_Info_Argsz_Offset            : constant := 0;
   IOMMU_Info_Flags_Offset            : constant := 4;
   IOMMU_Info_Page_Sizes_Offset       : constant := 8;
   IOMMU_Info_Cap_Offset_Offset       : constant := 16;

   DMA_Map_Size                       : constant := 32;
   DMA_Map_Argsz_Offset               : constant := 0;
   DMA_Map_Flags_Offset               : constant := 4;
   DMA_Map_Vaddr_Offset               : constant := 8;
   DMA_Map_IOVA_Offset                : constant := 16;
   DMA_Map_Size_Offset                : constant := 24;

   DMA_Unmap_Size                     : constant := 24;
   DMA_Unmap_Argsz_Offset             : constant := 0;
   DMA_Unmap_Flags_Offset             : constant := 4;
   DMA_Unmap_IOVA_Offset              : constant := 8;
   DMA_Unmap_Size_Offset              : constant := 16;

   Info_Cap_Header_Size               : constant := 8;
   Info_Cap_Header_ID_Offset          : constant := 0;
   Info_Cap_Header_Version_Offset     : constant := 2;
   Info_Cap_Header_Next_Offset        : constant := 4;

   ------------------------------------------------------------------
   --  Values from other headers this crate depends on
   ------------------------------------------------------------------

   --  MAP_SHARED, required for a BAR mapping.
   Mmap_Shared                        : constant := 16#1#;

   --  MAP_FAILED, which mmap returns as (void *) -1.
   Mmap_Failed_Sentinel               : constant := 16#FFFFFFFFFFFFFFFF#;

   --  PROT_READ.
   Prot_Read                          : constant := 16#1#;

   --  PROT_WRITE.
   Prot_Write                         : constant := 16#2#;

   --  EFD_CLOEXEC.
   Eventfd_Cloexec                    : constant := 16#80000#;

   --  EFD_NONBLOCK.
   Eventfd_Nonblock                   : constant := 16#800#;

   --  O_RDWR.
   Open_Read_Write                    : constant := 16#2#;

   --  O_CLOEXEC.
   Open_Cloexec                       : constant := 16#80000#;

end Flyology_VFIO.Thin.Constants;
