/*  Emits Flyology_VFIO.Thin.Constants from the host's Linux headers.
 *
 *  Every number this crate sends to the kernel comes from here. None is
 *  transcribed from documentation or memory: a wrong ioctl number produces
 *  EINVAL a long way from the mistake, and a wrong struct offset produces a
 *  kernel reading one field where another was meant.
 *
 *  Struct sizes and field offsets are emitted alongside the request numbers
 *  so that the Ada representation clauses can be checked against C at
 *  compile time rather than trusted. GNAT's 'Size excludes trailing padding
 *  where C's sizeof includes it, so the Ada side compares 'Object_Size.
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stddef.h>
#include <linux/vfio.h>
#include <sys/mman.h>
#include <sys/eventfd.h>

/*  Wraps a note into Ada comment lines no wider than the file's margin,
 *  so the generated source reads like the hand-written source beside it.  */
static void note_lines (const char *note)
{
  const int margin = 75;              /*  3 spaces + "--  " + text <= 79  */
  const char *p = note;

  while (*p)
    {
      int room = margin - 7, taken = 0, last_space = -1, i;

      for (i = 0; i < room && p[i]; i++)
        if (p[i] == ' ')
          last_space = i;

      if (p[i] == '\0')
        taken = i;
      else if (last_space > 0)
        taken = last_space;
      else
        taken = room;

      printf ("   --  %.*s\n", taken, p);
      p += taken;
      while (*p == ' ')
        p++;
    }
}

static void num (const char *name, unsigned long value, const char *note)
{
  note_lines (note);
  printf ("   %-34s : constant := %lu;\n\n", name, value);
}

static void hex (const char *name, unsigned long value, const char *note)
{
  note_lines (note);
  printf ("   %-34s : constant := 16#%lX#;\n\n", name, value);
}

int main (void)
{
  puts ("--  Generated by scripts/generate-constants.sh. Do not edit.");
  puts ("--");
  puts ("--  Regenerate on a Linux host, or through the repository's Linux");
  puts ("--  container, whenever the target kernel headers change. The");
  puts ("--  companion verify-constants.sh regenerates into a temporary file");
  puts ("--  and diffs, so drift between this file and the kernel is a test");
  puts ("--  failure rather than a surprise at run time.");
  puts ("package Flyology_VFIO.Thin.Constants");
  puts ("  with Preelaborate");
  puts ("is");
  puts ("");
  puts ("   ------------------------------------------------------------------");
  puts ("   --  Request numbers taken on a container file descriptor");
  puts ("   ------------------------------------------------------------------");
  puts ("");

  num ("Container_Get_API_Version", VFIO_GET_API_VERSION,
       "VFIO_GET_API_VERSION: no argument; the version is the result.");
  num ("Container_Check_Extension", VFIO_CHECK_EXTENSION,
       "VFIO_CHECK_EXTENSION: argument is an extension number, not a struct.");
  num ("Container_Set_IOMMU", VFIO_SET_IOMMU,
       "VFIO_SET_IOMMU: argument is an IOMMU type. Requires a group already "
       "attached.");
  num ("Container_Get_IOMMU_Info", VFIO_IOMMU_GET_INFO,
       "VFIO_IOMMU_GET_INFO: shares its number with "
       "VFIO_DEVICE_GET_PCI_HOT_RESET_INFO on a device fd.");
  num ("Container_Map_DMA", VFIO_IOMMU_MAP_DMA,
       "VFIO_IOMMU_MAP_DMA: shares its number with VFIO_DEVICE_PCI_HOT_RESET "
       "on a device fd.");
  num ("Container_Unmap_DMA", VFIO_IOMMU_UNMAP_DMA,
       "VFIO_IOMMU_UNMAP_DMA: shares its number with "
       "VFIO_DEVICE_QUERY_GFX_PLANE on a device fd.");

  puts ("   ------------------------------------------------------------------");
  puts ("   --  Request numbers taken on a group file descriptor");
  puts ("   ------------------------------------------------------------------");
  puts ("");
  num ("Group_Get_Status", VFIO_GROUP_GET_STATUS,
       "VFIO_GROUP_GET_STATUS: fills a struct carrying the viability flag.");
  num ("Group_Set_Container", VFIO_GROUP_SET_CONTAINER,
       "VFIO_GROUP_SET_CONTAINER: argument is a container fd, not a struct.");
  num ("Group_Unset_Container", VFIO_GROUP_UNSET_CONTAINER,
       "VFIO_GROUP_UNSET_CONTAINER: no argument.");
  num ("Group_Get_Device_FD", VFIO_GROUP_GET_DEVICE_FD,
       "VFIO_GROUP_GET_DEVICE_FD: argument is a NUL-terminated name; the new "
       "fd is the result.");

  puts ("   ------------------------------------------------------------------");
  puts ("   --  Request numbers taken on a device file descriptor");
  puts ("   ------------------------------------------------------------------");
  puts ("");
  num ("Device_Get_Info", VFIO_DEVICE_GET_INFO,
       "VFIO_DEVICE_GET_INFO: region and interrupt counts.");
  num ("Device_Get_Region_Info", VFIO_DEVICE_GET_REGION_INFO,
       "VFIO_DEVICE_GET_REGION_INFO: size, offset and flags of one region.");
  num ("Device_Get_IRQ_Info", VFIO_DEVICE_GET_IRQ_INFO,
       "VFIO_DEVICE_GET_IRQ_INFO: vector count and capabilities of one index.");
  num ("Device_Set_IRQs", VFIO_DEVICE_SET_IRQS,
       "VFIO_DEVICE_SET_IRQS: struct with a variable-length tail of eventfds.");
  num ("Device_Reset", VFIO_DEVICE_RESET,
       "VFIO_DEVICE_RESET: no argument. Bus mastering must be re-enabled "
       "afterwards.");

  puts ("   ------------------------------------------------------------------");
  puts ("   --  IOMMU types and extensions");
  puts ("   ------------------------------------------------------------------");
  puts ("");
  num ("API_Version", VFIO_API_VERSION,
       "The only API version this interface has ever had.");
  num ("Type1_IOMMU", VFIO_TYPE1_IOMMU, "The original type1 IOMMU.");
  num ("Type1_V2_IOMMU", VFIO_TYPE1v2_IOMMU,
       "Type1 version 2, which this crate requires.");
  num ("No_IOMMU", VFIO_NOIOMMU_IOMMU,
       "No-IOMMU mode, which supports no ioctl beyond CHECK_EXTENSION and in "
       "which a device consumes physical addresses. Not usable here.");

  puts ("   ------------------------------------------------------------------");
  puts ("   --  Flags");
  puts ("   ------------------------------------------------------------------");
  puts ("");
  hex ("Group_Flag_Viable", VFIO_GROUP_FLAGS_VIABLE,
       "Every device in the IOMMU group is bound to vfio-pci or unbound.");
  hex ("Group_Flag_Container_Set", VFIO_GROUP_FLAGS_CONTAINER_SET,
       "The group is already attached to a container.");
  hex ("Device_Flag_Reset", VFIO_DEVICE_FLAGS_RESET, "The device can reset.");
  hex ("Device_Flag_PCI", VFIO_DEVICE_FLAGS_PCI, "The device is vfio-pci.");
  hex ("Region_Flag_Read", VFIO_REGION_INFO_FLAG_READ, "Readable with pread.");
  hex ("Region_Flag_Write", VFIO_REGION_INFO_FLAG_WRITE,
       "Writable with pwrite.");
  hex ("Region_Flag_Mmap", VFIO_REGION_INFO_FLAG_MMAP,
       "Mappable. Absent for config space and for I/O port BARs.");
  hex ("Region_Flag_Caps", VFIO_REGION_INFO_FLAG_CAPS,
       "The reply carries a capability chain, which needs a second call.");
  hex ("DMA_Flag_Read", VFIO_DMA_MAP_FLAG_READ, "The device may read.");
  hex ("DMA_Flag_Write", VFIO_DMA_MAP_FLAG_WRITE, "The device may write.");
  hex ("IRQ_Set_Data_None", VFIO_IRQ_SET_DATA_NONE, "No data tail.");
  hex ("IRQ_Set_Data_Eventfd", VFIO_IRQ_SET_DATA_EVENTFD,
       "The tail is an array of eventfd descriptors.");
  hex ("IRQ_Set_Action_Trigger", VFIO_IRQ_SET_ACTION_TRIGGER,
       "Set what the interrupt triggers.");
  hex ("IRQ_Set_Action_Mask", VFIO_IRQ_SET_ACTION_MASK,
       "Mask an interrupt.");
  hex ("IRQ_Set_Action_Unmask", VFIO_IRQ_SET_ACTION_UNMASK,
       "Unmask an interrupt. An automasked index, which is what a legacy "
       "pin interrupt is, stays masked after each delivery until this is "
       "sent, so a handler that never unmasks receives exactly one "
       "interrupt and then silence.");
  hex ("IRQ_Info_Eventfd", VFIO_IRQ_INFO_EVENTFD,
       "This interrupt index can signal an eventfd.");
  hex ("IOMMU_Info_Page_Sizes", VFIO_IOMMU_INFO_PGSIZES,
       "The iova_pgsizes field is valid.");

  puts ("   ------------------------------------------------------------------");
  puts ("   --  PCI region and interrupt indices");
  puts ("   ------------------------------------------------------------------");
  puts ("");
  num ("PCI_BAR0_Region", VFIO_PCI_BAR0_REGION_INDEX, "First base address register.");
  num ("PCI_ROM_Region", VFIO_PCI_ROM_REGION_INDEX, "Expansion ROM.");
  num ("PCI_Config_Region", VFIO_PCI_CONFIG_REGION_INDEX,
       "Configuration space. Never mappable: read and written with "
       "pread and pwrite at this region's offset.");
  num ("PCI_Region_Count", VFIO_PCI_NUM_REGIONS, "Regions a PCI device has.");
  num ("PCI_INTX_IRQ", VFIO_PCI_INTX_IRQ_INDEX, "Legacy pin interrupt.");
  num ("PCI_MSI_IRQ", VFIO_PCI_MSI_IRQ_INDEX, "MSI.");
  num ("PCI_MSIX_IRQ", VFIO_PCI_MSIX_IRQ_INDEX, "MSI-X.");
  num ("PCI_IRQ_Count", VFIO_PCI_NUM_IRQS, "Interrupt indices a PCI device has.");

  puts ("   ------------------------------------------------------------------");
  puts ("   --  Struct sizes and field offsets, for the layout assertions");
  puts ("   --");
  puts ("   --  The Ada records in the parent package pin their layout with");
  puts ("   --  representation clauses and check it against these with");
  puts ("   --  pragma Compile_Time_Error, so a kernel that moves a field");
  puts ("   --  breaks the build rather than the device.");
  puts ("   ------------------------------------------------------------------");
  puts ("");

#define SZ(ada, t) printf ("   %-34s : constant := %lu;\n", ada "_Size", \
                           (unsigned long) sizeof (t))
#define OF(ada, t, f) printf ("   %-34s : constant := %lu;\n", \
                              ada "_Offset", (unsigned long) offsetof (t, f))

  SZ ("Group_Status", struct vfio_group_status);
  OF ("Group_Status_Argsz", struct vfio_group_status, argsz);
  OF ("Group_Status_Flags", struct vfio_group_status, flags);
  puts ("");
  SZ ("Device_Info", struct vfio_device_info);
  OF ("Device_Info_Argsz", struct vfio_device_info, argsz);
  OF ("Device_Info_Flags", struct vfio_device_info, flags);
  OF ("Device_Info_Num_Regions", struct vfio_device_info, num_regions);
  OF ("Device_Info_Num_IRQs", struct vfio_device_info, num_irqs);
  puts ("");
  SZ ("Region_Info", struct vfio_region_info);
  OF ("Region_Info_Argsz", struct vfio_region_info, argsz);
  OF ("Region_Info_Flags", struct vfio_region_info, flags);
  OF ("Region_Info_Index", struct vfio_region_info, index);
  OF ("Region_Info_Cap_Offset", struct vfio_region_info, cap_offset);
  OF ("Region_Info_Size", struct vfio_region_info, size);
  OF ("Region_Info_Offset", struct vfio_region_info, offset);
  puts ("");
  SZ ("IRQ_Info", struct vfio_irq_info);
  OF ("IRQ_Info_Argsz", struct vfio_irq_info, argsz);
  OF ("IRQ_Info_Flags", struct vfio_irq_info, flags);
  OF ("IRQ_Info_Index", struct vfio_irq_info, index);
  OF ("IRQ_Info_Count", struct vfio_irq_info, count);
  puts ("");
  /*  vfio_irq_set ends in a flexible array member, so sizeof is the header
   *  alone and argsz must be the header plus the payload the flags imply.  */
  SZ ("IRQ_Set_Header", struct vfio_irq_set);
  OF ("IRQ_Set_Argsz", struct vfio_irq_set, argsz);
  OF ("IRQ_Set_Flags", struct vfio_irq_set, flags);
  OF ("IRQ_Set_Index", struct vfio_irq_set, index);
  OF ("IRQ_Set_Start", struct vfio_irq_set, start);
  OF ("IRQ_Set_Count", struct vfio_irq_set, count);
  OF ("IRQ_Set_Data", struct vfio_irq_set, data);
  puts ("");
  SZ ("IOMMU_Info", struct vfio_iommu_type1_info);
  OF ("IOMMU_Info_Argsz", struct vfio_iommu_type1_info, argsz);
  OF ("IOMMU_Info_Flags", struct vfio_iommu_type1_info, flags);
  OF ("IOMMU_Info_Page_Sizes", struct vfio_iommu_type1_info, iova_pgsizes);
  OF ("IOMMU_Info_Cap_Offset", struct vfio_iommu_type1_info, cap_offset);
  puts ("");
  SZ ("DMA_Map", struct vfio_iommu_type1_dma_map);
  OF ("DMA_Map_Argsz", struct vfio_iommu_type1_dma_map, argsz);
  OF ("DMA_Map_Flags", struct vfio_iommu_type1_dma_map, flags);
  OF ("DMA_Map_Vaddr", struct vfio_iommu_type1_dma_map, vaddr);
  OF ("DMA_Map_IOVA", struct vfio_iommu_type1_dma_map, iova);
  OF ("DMA_Map_Size", struct vfio_iommu_type1_dma_map, size);
  puts ("");
  SZ ("DMA_Unmap", struct vfio_iommu_type1_dma_unmap);
  OF ("DMA_Unmap_Argsz", struct vfio_iommu_type1_dma_unmap, argsz);
  OF ("DMA_Unmap_Flags", struct vfio_iommu_type1_dma_unmap, flags);
  OF ("DMA_Unmap_IOVA", struct vfio_iommu_type1_dma_unmap, iova);
  OF ("DMA_Unmap_Size", struct vfio_iommu_type1_dma_unmap, size);
  puts ("");
  SZ ("Info_Cap_Header", struct vfio_info_cap_header);
  OF ("Info_Cap_Header_ID", struct vfio_info_cap_header, id);
  OF ("Info_Cap_Header_Version", struct vfio_info_cap_header, version);
  OF ("Info_Cap_Header_Next", struct vfio_info_cap_header, next);
  puts ("");

  puts ("   ------------------------------------------------------------------");
  puts ("   --  Values from other headers this crate depends on");
  puts ("   ------------------------------------------------------------------");
  puts ("");
  hex ("Mmap_Shared", MAP_SHARED, "MAP_SHARED, required for a BAR mapping.");
  hex ("Mmap_Failed_Sentinel", (unsigned long) -1L,
       "MAP_FAILED, which mmap returns as (void *) -1.");
  hex ("Prot_Read", PROT_READ, "PROT_READ.");
  hex ("Prot_Write", PROT_WRITE, "PROT_WRITE.");
  hex ("Eventfd_Cloexec", EFD_CLOEXEC, "EFD_CLOEXEC.");
  hex ("Eventfd_Nonblock", EFD_NONBLOCK, "EFD_NONBLOCK.");
  hex ("Open_Read_Write", 02, "O_RDWR.");
  hex ("Open_Cloexec", 02000000, "O_CLOEXEC.");

  puts ("end Flyology_VFIO.Thin.Constants;");
  return 0;
}
